stages:

- stage: Versioning
  displayName: Versioning
  jobs:
    
  # Build number to use when on the main branch
  - job: Build_Main_Version_Number
    displayName: Build version for main branch
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
        patch: $[counter(variables['minor'], 0)]
    steps:
      - checkout: none
      - bash: |
          echo "Generating Build Number"
          echo "##vso[build.updatebuildnumber]$(major).$(minor).$(patch)"
        name: SetMainBuildName
          
  # Slightly different build number when this is on any other branch than main
  - job: Build_Branch_Version_Number
    displayName: Build version for other branch
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
        prpatch: $[counter(variables['build.sourcebranchname'], 0)]
    steps:
      - checkout: none
      - bash: |
          echo "Generating Build Number"
          echo "##vso[build.updatebuildnumber]$(major).$(minor)-PullRequest.$(prpatch)"
        condition: eq(variables['Build.Reason'], 'PullRequest')
        name: SetPRBuildName
      - bash: |
          echo "Generating Build Number"
          echo "##vso[build.updatebuildnumber]$(major).$(minor)-$(Build.SourceBranchName).$(prpatch)"
        condition: ne(variables['Build.Reason'], 'PullRequest')
        name: SetBranchBuildName