trigger:
  batch: true
  branches:
    include:
      - master
  
pool:
  vmImage: 'ubuntu-18.04'

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

stages:
  - stage: Build
    displayName: 'Build Code and Run Unit Tests'
    variables:
      - name: 'buildConfiguration'
        value: 'Release'
    jobs:
  
    - job: Build
      displayName: 'Build Code and run Unit Tests'
      steps:

      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: 'restore'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: 'build'
          projects: 'src/affolterNET.Data.sln'
          arguments: '--configuration $(buildConfiguration) /p:SourceRevisionId=$(SourceVersionShort)'

      - task: DotNetCoreCLI@2
        displayName: 'run unit tests'
        inputs:
          command: test
          projects: '**/Test/*.Test/*.Test.csproj'
          arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" --settings src/Test/coverlet.runsettings -- RunConfiguration.DisableAppDomain=true'

      - task: DotNetCoreCLI@2
        displayName: 'nuget pack affolterNET.Data'
        inputs:
          command: 'pack'
          packagesToPack: 'src/affolterNET.Data/affolterNET.Data.csproj'
          nobuild: true
          versioningScheme: 'off'

      - task: DotNetCoreCLI@2
        displayName: 'nuget pack affolterNET.Data.TestHelpers'
        inputs:
          command: 'pack'
          packagesToPack: 'src/affolterNET.Data.TestHelpers/affolterNET.Data.TestHelpers.csproj'
          nobuild: true
          versioningScheme: 'off'

      - task: DotNetCoreCLI@2
        displayName: 'nuget push'
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: 'e27a58c6-e50a-44d8-a798-55c10e05709c'
          