trigger:
  batch: true
  branches:
    include:
      - master
  
pool:
  vmImage: 'ubuntu-18.04'

variables:
  - group: affolternet-data-settings

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

stages:

  - template: _versioning.yml

  - stage: Build
    displayName: 'Build Code and Run Unit Tests'
    variables:
      - name: 'buildConfiguration'
        value: 'Release'

    jobs:
  
    - job: Build
      displayName: 'Build Code and run Unit Tests'
      variables:
        informationalVersion: $(Build.BuildNumber)
        assemblyVersion: $(Build.BuildNumber)
        assemblyDefaultVersion: $[ format('{0}.{1}', variables['major'], variables['minor']) ]

      steps:

      - bash: echo '##vso[task.setvariable variable=assemblyVersion]$(assemblyDefaultVersion)'
        condition: contains(variables['Build.BuildNumber'], '-')

      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '5.x'
          includePreviewVersions: false

      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: 'restore'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: 'build'
          projects: 'src/affolterNET.Data.sln'
          arguments: '--configuration $(buildConfiguration) -p:Version=$(assemblyVersion) -p:InformationalVersion=$(informationalVersion)'

      - task: DotNetCoreCLI@2
        displayName: 'run unit tests'
        inputs:
          command: test
          projects: '**/Test/*.Test/*.Test.csproj'
          arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" --settings src/Test/coverlet.runsettings'

      - task: DotNetCoreCLI@2
        displayName: 'nuget pack'
        inputs:
          command: 'pack'
          packagesToPack: 'src/**/*.csproj;!**/Test/*.csproj'
          versioningScheme: 'byBuildNumber'

      - task: DotNetCoreCLI@2
        displayName: 'nuget push'
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: 'e27a58c6-e50a-44d8-a798-55c10e05709c'

      - task: git-tag-on-release-task@9
        displayName: "add tag to git"
        inputs:
          staticTagName: "nuget-$(Build.BuildNumber)"
          